[package]
name = "lazarus-cli"
description = "Command-line client for Lazarus."
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
clap.workspace = true
protocol-rs = { path = "../protocol-rs" }
tonic.workspace = true
tokio.workspace = true

[lints]
workspace = true
