// @generated by scripts/generate-protocol-bindings.mjs from
// packages/protocol-ts/src/registry (the TypeScript/Zod source of truth).
// DO NOT EDIT BY HAND. Regenerate with:
//   pnpm --filter @lazarus/protocol-ts gen:bindings
//
// The manifest fingerprint equals the SHA-256 of the canonical JSON of the
// sorted method snapshots computed by the TypeScript registry
// (`snapshotManifest()`); the golden copy used for verification lives at
// crates/protocol-rs/tests/protocol_manifest.json.

/// Transport shape of a protocol method.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum MethodKind {
    Unary,
    ServerStreaming,
}

impl MethodKind {
    pub fn as_str(self) -> &'static str {
        match self {
            MethodKind::Unary => "unary",
            MethodKind::ServerStreaming => "serverStreaming",
        }
    }
}

/// One generated binding: the per-method contract anchor on the Rust side.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MethodBinding {
    pub name: &'static str,
    pub kind: MethodKind,
    pub major: u32,
    pub minor: u32,
    pub optional: bool,
    pub fallback: Option<&'static str>,
    /// SHA-256 (hex) of the canonical JSON Schema of the request.
    pub request_fingerprint: &'static str,
    /// SHA-256 (hex) of the canonical JSON Schema of the response.
    pub response_fingerprint: &'static str,
}

/// Manifest fingerprint over all method bindings (see header).
pub const MANIFEST_FINGERPRINT: &str =
    "9b2843218d5224684e6fcc9089dd2d3b9ae4b368fce844cfc612d05858a1772c";

/// Generated method bindings, sorted by name.
pub const METHOD_BINDINGS: &[MethodBinding] = &[
    MethodBinding {
        name: "system.getInfo",
        kind: MethodKind::Unary,
        major: 1,
        minor: 0,
        optional: false,
        fallback: None,
        request_fingerprint: "93ab7499dc3c616f8db8780fed0d9f69270803cda913882ad2ef3943db8d7225",
        response_fingerprint: "07dedac11947172fe27a313fe993236d4ef5c8b750384dee0a7eeb8ca78d2174",
    },
    MethodBinding {
        name: "system.health",
        kind: MethodKind::Unary,
        major: 1,
        minor: 0,
        optional: false,
        fallback: None,
        request_fingerprint: "93ab7499dc3c616f8db8780fed0d9f69270803cda913882ad2ef3943db8d7225",
        response_fingerprint: "c3de975c21db849a1fd07c2110d5719416b6148d2f76938314c9f21b17a675b2",
    },
    MethodBinding {
        name: "system.subscribeEvents",
        kind: MethodKind::ServerStreaming,
        major: 1,
        minor: 0,
        optional: false,
        fallback: None,
        request_fingerprint: "93ab7499dc3c616f8db8780fed0d9f69270803cda913882ad2ef3943db8d7225",
        response_fingerprint: "da7f478a78a2588a466b3af3e61c6e00a8259e4fc31ec3a5f655525fb97e728e",
    },
    MethodBinding {
        name: "task.list",
        kind: MethodKind::Unary,
        major: 1,
        minor: 2,
        optional: false,
        fallback: None,
        request_fingerprint: "90612587a3c742d829518ac8ece6e29ee0f409ee8df95a04537ed01d5e0e7405",
        response_fingerprint: "0a11e49d0b1087bb8f99f85d22ae68b727fa91b58e1361d0b781f028bdee1c9e",
    },
    MethodBinding {
        name: "workspace.list",
        kind: MethodKind::Unary,
        major: 1,
        minor: 0,
        optional: false,
        fallback: None,
        request_fingerprint: "90612587a3c742d829518ac8ece6e29ee0f409ee8df95a04537ed01d5e0e7405",
        response_fingerprint: "d31af4ef4776c62b095b7c02bc368cd841da3f659ae95b1ad13706d07d2aeb4d",
    },
];

/// Frozen released-floor method names every supported Host keeps serving.
pub const RELEASED_FLOOR: &[&str] = &[
    "system.getInfo",
    "system.health",
    "system.subscribeEvents",
    "task.list",
    "workspace.list",
];

/// Older peer minors each method interoperates with through a declared
/// TypeScript bridge, sorted by method then minor. Derived from the bridge
/// registry in the source-of-truth package; a peer advertising one of these
/// minors negotiates at that minor instead of being rejected.
#[rustfmt::skip]
pub const BRIDGED_PEER_MINORS: &[(&str, &[u32])] = &[
    ("task.list", &[0]),
];

/// One declarative bridge step. Plain data only: the Host executes these
/// steps over response payloads, mirroring the TypeScript executor exactly.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BridgeStep {
    /// Removes named top-level fields added after the older peer minor.
    OmitResponseFields(&'static [&'static str]),
}

/// One generated bridge binding: the executable adapter keeping an older
/// peer minor interoperable with its method's current minor.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct MethodBridgeBinding {
    pub name: &'static str,
    pub older_minor: u32,
    pub steps: &'static [BridgeStep],
}

/// Declared bridges, sorted by name then older minor.
#[rustfmt::skip]
pub const METHOD_BRIDGES: &[MethodBridgeBinding] = &[
    MethodBridgeBinding {
        name: "task.list",
        older_minor: 0,
        steps: &[
            BridgeStep::OmitResponseFields(&["servedAtUnixMs"]),
        ],
    },
];

/// Declared-bridge peer minors for a method; empty when none are declared.
pub fn bridged_peer_minors(name: &str) -> &'static [u32] {
    BRIDGED_PEER_MINORS
        .iter()
        .find(|(method, _)| *method == name)
        .map(|(_, minors)| *minors)
        .unwrap_or(&[])
}

/// The declared bridge steps adapting `name` responses down to an older
/// peer minor; empty when no bridge is declared for that pair.
pub fn bridge_steps(name: &str, older_minor: u32) -> &'static [BridgeStep] {
    METHOD_BRIDGES
        .iter()
        .find(|bridge| bridge.name == name && bridge.older_minor == older_minor)
        .map(|bridge| bridge.steps)
        .unwrap_or(&[])
}

/// Looks up a generated binding by fully qualified method name.
pub fn binding_by_name(name: &str) -> Option<&'static MethodBinding> {
    METHOD_BINDINGS.iter().find(|binding| binding.name == name)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn bindings_are_sorted_and_unique() {
        let names: Vec<&str> = METHOD_BINDINGS.iter().map(|b| b.name).collect();
        let mut sorted = names.clone();
        sorted.sort_unstable();
        sorted.dedup();
        assert_eq!(names, sorted, "bindings must be sorted by unique name");
    }

    #[test]
    fn released_floor_is_covered_by_bindings() {
        for name in RELEASED_FLOOR {
            assert!(
                binding_by_name(name).is_some(),
                "released-floor method {name} has no binding"
            );
        }
        assert_eq!(RELEASED_FLOOR.len(), METHOD_BINDINGS.len());
    }

    #[test]
    fn fingerprints_are_sha256_hex() {
        assert_eq!(MANIFEST_FINGERPRINT.len(), 64);
        assert!(MANIFEST_FINGERPRINT.chars().all(|c| c.is_ascii_hexdigit()));
        for binding in METHOD_BINDINGS {
            for fingerprint in [binding.request_fingerprint, binding.response_fingerprint] {
                assert_eq!(
                    fingerprint.len(),
                    64,
                    "{:?} fingerprint length",
                    binding.name
                );
                assert!(
                    fingerprint.chars().all(|c| c.is_ascii_hexdigit()),
                    "{:?} fingerprint charset",
                    binding.name
                );
            }
            if binding.fallback.is_some() {
                assert!(binding.optional, "only optional methods declare fallbacks");
            }
        }
    }

    #[test]
    fn lookup_roundtrips() {
        let health = binding_by_name("system.health").expect("health binding");
        assert_eq!(health.kind, MethodKind::Unary);
        assert_eq!(health.major, 1);
        assert_eq!(health.minor, 0);
        let subscribe = binding_by_name("system.subscribeEvents").expect("subscribe binding");
        assert_eq!(subscribe.kind, MethodKind::ServerStreaming);
        assert!(binding_by_name("no.such_method").is_none());
    }

    #[test]
    fn bridged_minors_reference_bindings_and_stay_sorted() {
        let names: Vec<&str> = BRIDGED_PEER_MINORS.iter().map(|(n, _)| *n).collect();
        let mut sorted_names = names.clone();
        sorted_names.sort_unstable();
        sorted_names.dedup();
        assert_eq!(
            names, sorted_names,
            "bridge entries must be sorted by unique method"
        );
        for (name, minors) in BRIDGED_PEER_MINORS {
            assert!(
                binding_by_name(name).is_some(),
                "bridge for unknown binding {name}"
            );
            assert!(!minors.is_empty(), "{name} declares an empty bridge table");
            let mut sorted = minors.to_vec();
            sorted.sort_unstable();
            sorted.dedup();
            assert_eq!(
                *minors,
                sorted.as_slice(),
                "{name} bridge minors sorted/unique"
            );
        }
        for binding in METHOD_BINDINGS {
            let looked_up = bridged_peer_minors(binding.name);
            let expected = BRIDGED_PEER_MINORS
                .iter()
                .find(|(n, _)| *n == binding.name)
                .map(|(_, m)| *m)
                .unwrap_or(&[]);
            assert_eq!(looked_up, expected, "bridged_peer_minors({})", binding.name);
        }
    }

    #[test]
    fn bridge_steps_match_bridged_peer_minors() {
        for bridge in METHOD_BRIDGES {
            assert!(
                binding_by_name(bridge.name).is_some(),
                "bridge for unknown binding {}",
                bridge.name
            );
            assert!(
                bridged_peer_minors(bridge.name).contains(&bridge.older_minor),
                "{} declares steps for unbridged minor {}",
                bridge.name,
                bridge.older_minor
            );
        }
        for (name, minors) in BRIDGED_PEER_MINORS {
            for minor in *minors {
                assert!(
                    METHOD_BRIDGES
                        .iter()
                        .any(|bridge| bridge.name == *name && bridge.older_minor == *minor),
                    "bridged minor {minor} of {name} has no executable steps"
                );
            }
        }
    }
}
